name: hello world
on:
  push: 
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
      - name: dungnguyen
      - run: echo hello world

  day:
    runs-on: ubuntu-latest
    steps: 
      - name: today
      - run: echo "TODAY=$(data + %y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
